<?php
function dna_menu() {
    $items['dna'] = array(
        'title' => 'DNA Completer',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['second_helix_page'] = array(
        'title' => "Here's your better half!",
        'page callback' => 'second_helix',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['dna'] = array(
        '#title' => 'Your Helix',
        '#type' => 'textfield',
        '#description' => t('Enter your helix sequence. This should consist of only the letters A, C, G, & T to represent the 4 nucleotides! (Separate the letter by spaces or commas or nothing at all...)'),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_letters'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Pair my helix!',
    );
    return $form;
}

function element_validate_letters($element) {
    // $inputNoPunct = preg_replace("#[[:punct:]]#", "", strtoupper($element));
    // $inputNoSpace = preg_replace(" ", "", $inputNoPunct);
    $element_array = str_split(strtoupper($element['#value']));
    $non_nucleotides = array(
        "B",
        "D",
        "E",
        "F",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
    );
    $count = 0;
    foreach ($element_array as $character) {
        if(in_array($character, $non_nucleotides)) {
            $count++;
        }
    }

    if($count > 0) {
        form_error($element, t("Remember, nucleotides are represented by only the letters A, C, G, & T. Please check your input for any off characters!"));
    }

    // if (strpbrk(strtoupper($element_string), $non_nucleotides) != FALSE) {
    //     form_error($element, t("Remember, nucleotides are represented by only the letters A, C, G, & T. Please check your input for any off characters!"));
    // }
}

// function
